version: "3.9"

services:
  addition:
    build:
      context: .
      dockerfile: addition/Dockerfile
    deploy:
      replicas: 1
        
  multiplication:
    build:
      context: .
      dockerfile: multiplication/Dockerfile
    deploy:
      replicas: 1
    depends_on:
      - storage-handler
      
  division:
    build:
      context: .
      dockerfile: division/Dockerfile
    deploy:
      replicas: 1

  subtraction:
    build:
      context: .
      dockerfile: subtraction/Dockerfile
    deploy:
      replicas: 1
    restart: on-failure
    
  storage-handler:
    build:
      context: .
      dockerfile: storage-handler/Dockerfile
    deploy:
      replicas: 1
    depends_on:
      - calculation-history-db
    restart: on-failure
    
  frontend:
    build:
      context: ./my-calculator-app/
      dockerfile: Dockerfile
    depends_on:
      - addition
      - subtraction
    
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    
  rmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=application
      - RABBITMQ_DEFAULT_PASS=pass
        
  nginx-proxy:
    image: nginx:alpine
    volumes:
    - ./nginx-config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "4200:80"
    depends_on:
      - frontend
      - addition
      - subtraction
      - multiplication
      - division
      - storage-handler

  calculation-history-db:
    image: "mysql"
    environment:
      MYSQL_DATABASE: "calculation-history-database"
      MYSQL_USER: "calculatorHistory"
      MYSQL_PASSWORD: "C@ch3d1v"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    ports:
      - "3306:3306"