version: "3.9"

services:
  addition:
    build:
      context: .
      dockerfile: addition/Dockerfile
    deploy:
      replicas: 3
    depends_on:
      - calculator-db

  subtraction:
    build:
      context: .
      dockerfile: subtraction/Dockerfile
    deploy:
      replicas: 3
    depends_on:
      - calculator-db
    restart: on-failure
    
  frontend:
    build:
      context: ./my-calculator-app/
      dockerfile: Dockerfile
    depends_on:
      - addition
      - subtraction
    
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    
  rmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=application
      - RABBITMQ_DEFAULT_PASS=pass
        
  nginx-proxy:
    image: nginx:alpine
    volumes:
    - ./nginx-config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "4200:80"
    depends_on:
      - frontend
      - addition

  calculator-db:
    image: "mysql"
    environment:
      MYSQL_DATABASE: "calculator_db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"